apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yuvraj8565
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: yuvraj8565/nginx_assesment
        ports:
        - containerPort: 80

